irib/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('process', views.process, name='process'),
    url(r'^validate/(?P<trans>.+)/$', views.validate, name='validate'),
    url(r'^feed/(?P<sent_text>.+)/(?P<actual_state>.+)/(?P<word_position>.+)/$', views.feed, name='feed'),
    url(r'^missing_pos/(?P<missing_word>.+)/$', views.missing_pos, name='missing_pos'),
    # path('feed/<int:actual_state>/<int:word_position>/<str:sent_text>', views.feed, name='feed')
]

iribli/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('irib/', include('irib.urls')),
]

irib/forms.py
from django import forms
from .models import *
import pyarabic.araby as araby
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Button, HTML, Field, ButtonHolder
from django.core.exceptions import ValidationError

class AddRule(forms.Form):
    state = forms.ModelChoiceField(label='الإعراب المناسب :', 
        help_text="إن لم يوجد إعراب مناسب، يرجى ترك الإختيار فارغاً و إدخال الإعراب يدوياً مع إختيار معلومات طرف الكلام.", 
        required=False, queryset=State.objects.all(), widget=forms.Select(attrs={'dir': "rtl", 'lang': 'AR', 'style': 'width: 100%;'}))
    pos = forms.CharField(label="معلومات طرف الكلام :", required=False, widget=forms.Select(choices=[('', '-------')], attrs={'dir': "rtl", 'lang': 'AR', 'style': 'width: 100%;'}))
    label = forms.CharField(label='إدخال الإعراب :', max_length = 250, required=False, widget=forms.TextInput(attrs={'dir': "rtl", 'lang': 'AR', 'style': 'width: 100%;'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Div(
                Div('state', css_class="col-sm-12"),
                css_class = 'row state'
            ),
            Div(
                Div('pos', css_class="col-sm-12"),
                css_class = 'row pos'
            ),
            Div(
                Div('label', css_class="col-sm-12"),
                css_class = 'row label'
            ),
            Div(
                Submit('submit', 'قدم', css_class="col-sm-6", style="display: block; margin-top:15px; margin-left: auto; margin-right: auto;"),
                css_class = 'row'
            ),
            
        )
        self.helper.form_show_errors = False
    
    def clean(self):
        cleaned_data = super().clean()
        state = cleaned_data.get("state")
        pos = cleaned_data.get("pos")
        label = cleaned_data.get("label")

        if not state:
            # Only do something if both fields are valid so far.
            if not (pos and label):
                raise ValidationError(
                    "يرجى ملأ المعلومات"
                )

    




        

irib/views.py
from django.shortcuts import render, redirect
from .processor import *
from .rule_manager import *
from .models import RulePack
from .forms import AddRule
import string

TRANSLATE = {
    "nominal": "إسم",
    "verbs": "فعل",
    "tool": "أداة",
    "except": "إسم خاص",
    "prop": "إسم علم",
    "Comparative": "مقارنة",
    "Masdar": "مصدر", 
    "Miscellaneous": "متنوع", 
    "active_participle": "نعت", 
    "artificial_masdar": "مصدر صناعي", 
    "brokenPlural": "جمع التكسير", 
    "instrument": "إسم أداة", 
    "marrah": "إسم مرة", 
    "mubalagah": "مبالغة", 
    "mushabbaha": "مشبهة", 
    "nisbah": "نسبة", 
    "passive_participle": "النعت السلبي", 
    "place": "إسم مكان", 
    "regular_feminine_dual": "مثنى مؤنث",
    "singular_forms-broken_plural_forms": "إسم مفرد", 
    "singular_forms-fem_plural_forms": "إسم مؤنث", 
    "singular_forms-no_plural_forms": "...", 
    "singular_forms-reg_plural_forms": "...",
    "adjectival": "صفة",
    "nominal": "إسم",
    "nominal/adjectival": "إسم - صفة",
    "participial": "مكون من إسم الفاعل أو المفعول",
    "1": "فعل من الشكل 1",
    "2": "فعل من الشكل 2",
    "3": "فعل من الشكل 3",
    "4": "فعل من الشكل 4",
    "5": "فعل من الشكل 5",
    "6": "فعل من الشكل 6",
    "7": "فعل من الشكل 7",
    "8": "فعل من الشكل 8",
    "9": "فعل من الشكل 9",
    "present": "فعل مضارع",
    "نسبة إلى اسم علم": "نسبة إلى اسم علم",
    "اسم علم": "اسم علم", 
    "اسم الجلالة": "اسم الجلالة", 
    "raf3": "رفع",
    "nasb": "نصب",
    "jarr": "جر",
    "jazm": "جزم",
    "word_type": "نوع الكلمة",
    "word_subtype": "تكمبل نوع الكلمة",
    "halat_al_irab": "حالة الإعراب",
    "is_muaaraf": "معرف",
    "True": "نعم",
    "False": "لا"
}

def home(request):

    return render(request, 'irib/home.html', locals())

def process(request):
    RP = RulePack.objects.get(active=True)
    start_state = State.objects.get(rule_pack=RP, label="START")
    if request.POST:
        try:
            text_phrase = request.POST['sent_text'].translate(str.maketrans('', '', string.punctuation))
            phrase = araby.tokenize(text_phrase, conditions=araby.is_arabicrange)
            txt_phrase = " ".join(phrase)
            posed_phrase = []
            posed_phrase_list = []
            accepted = []
            for w in phrase:
                print(w)
                pos = pos_word(w)
                posed_phrase.append({'word': w, 'pos': pos})
                posed_phrase_list.append(pos)
            sent_combinations = to_combs(posed_phrase_list)
            for sent in sent_combinations:
                tmp = RP.r_parser(sent, actual_state=start_state)
                proposition = []
                trans = []
                for t in tmp:
                    # print(t)
                    if t:
                        for i, irab in enumerate(t[1:]):
                            proposition.append({
                                'word': phrase[i], 
                                'irab': irab,
                                'trans': RP.get_transition(
                                    from_state=t[i], 
                                    to_state=t[i+1], **sent[i])
                                })
                            trans.append(RP.get_transition(
                                    from_state=t[i], 
                                    to_state=t[i+1], **sent[i]).id)
                    if proposition:
                        if {'proposition': proposition, 'trans': trans} not in accepted:
                            accepted.append({'proposition': proposition, 'trans': trans})
            if not accepted:
                return redirect('feed', sent_text=" ".join(phrase), actual_state=start_state.id, word_position=0)
                # accepted += RP.r_parser(sent)

        except RulePack.DoesNotExist:
            print("No RPACK !! Handle This !")
            # return redirect("activate_rpack")

    return render(request, 'irib/process.html', locals())


def validate(request, trans):
    
    trans = [int(t) for t in trans.split(',')]
    transitions = Transition.objects.filter(id__in=trans)
    for t in transitions:
        t.occ += 1
        t.save()
    
    return redirect('home')


def feed(request, sent_text, actual_state, word_position):
    RP = RulePack.objects.get(active=True)
    phrase = araby.tokenize(sent_text)
    word_position = int(word_position)
    state = State.objects.get(pk=actual_state)
    
    form = AddRule(request.POST or None)

    potential_states = []

    tmp_pos = pos_word(phrase[word_position])
    if not tmp_pos:
        MissingPos.objects.create(word=phrase[word_position])
        return redirect("missing_pos", missing_word=phrase[word_position])

    if form.is_valid():
        if form.cleaned_data['state']: # Etat éxistant ------------------------------------
            for t in state.next_transitions.filter(to_state=form.cleaned_data['state']): ### Incrémenter le poids de la transition...
                t.occ += 1
                t.save()
            if word_position == len(phrase) - 1:
                form.cleaned_data['state'].is_end = True
                form.cleaned_data['state'].save()
                return redirect('home')
            return redirect('feed', sent_text=sent_text, actual_state=form.cleaned_data['state'].id, word_position=word_position+1)
        elif form.cleaned_data['pos'] != -1 and form.cleaned_data['label']: # Etat non éxistant et informations de l'irab saisis --
            is_end = False; is_start=False
            if word_position == len(phrase) - 1:
                is_end = True
            if word_position == 0:
                is_start = True
            s = RP.add_state(label=form.cleaned_data['label'], is_start=is_start, is_end=is_end)
            t = RP.add_transition(from_state=state, to_state=s, **tmp_pos[int(form.cleaned_data['pos'])])
            if is_end:
                return redirect('home')
            else:
                return redirect('feed', sent_text=sent_text, actual_state=s.id, word_position=word_position+1)
        else: # Si pas de transition ni de P.O.S. possible pour le mot actuel : On s'éxcuse auprés de l'utilisateur et on stocke le mot qui pose probléme pour essayer de le régler plutard.
            MissingPos.objects.create(word=phrase[word_position])
            return redirect("missing_pos", phrase[word_position])
    
    for pos in tmp_pos:
        trans = state.next_transitions.filter(**pos)
        for t in trans:
            potential_states.append(t.to_state)
    POS_CHOICES = []
    for i, p in enumerate(tmp_pos):
        POS_CHOICES.append(
            (
                i,
                " | ".join(
                        [
                            TRANSLATE[key] + " : "+ TRANSLATE[str(value)] 
                            if key in TRANSLATE.keys() and str(value) in TRANSLATE.keys()
                            else key + " : "+ str(value)
                            for key, value in p.items()
                        ]
                    )
            )
        )
    form.fields['state'].queryset = State.objects.filter(pk__in=[s.id for s in potential_states])
    form.fields['pos'].widget.choices += POS_CHOICES

        
    
    return render(request, 'irib/feed.html', locals())


def missing_pos(request, missing_word):
    out_dec = decoupage(missing_word)
    out_sch = attach_sheme(out_dec)
    out_rcn = attach_racine(out_sch)
    error_msg = "Découpage : "+str(out_dec)+" --- Recherche du schème : \n"+str(out_sch)+" --- Recherche de la racine : \n"+str(out_rcn)+"\n"
    return render(request, 'irib/missing_pos.html', locals())

irib/templates/irib/feed.html
{% extends 'index.html' %}

{% block 'content' %}
    {% load crispy_forms_tags %}
    <p dir="rtl" lang='AR'>
    يرجى إختيار المعلومات الصحيحة لكل كلمة و إدخال الإعراب المناسب.<br>
    ستسجل المعلومات و سيتم طرحها في الحالات المماثلة في المستقبل.<br>
    شكراً !
    </p>
    <p dir="rtl" lang='AR'>الجملة : 
        {% for w in phrase %}
            {% if forloop.counter0 == word_position %} <U>{{w}}</U> 
            {% else %} {{w}}
            {% endif %}
        {% endfor %}.
    </p>
    <div>
    <form dir="rtl" lang='ar' method="POST", action="{% url 'feed' sent_text actual_state word_position %}">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p><br><br>
        {% crispy form form.helper %}
    </form>
    </div>
{% endblock %}
{% block 'js' %}
    <script>
    
        document.querySelector('#nav_feed').classList += ' active';

        var state = document.querySelector('#id_state');
        if(state.length == 0){
            $('.state').hide();
        }else{

            state.addEventListener('change', function(e){
                if(state.value ){
                    $('.pos').hide();
                    $('.label').hide();
                }
                else{
                    $('.pos').show();
                    $('.label').show();
                }
            });
        }

    </script>
{% endblock 'js' %}

irib/templates/irib/home.html
{% extends 'index.html' %}

{% block 'content' %}
    <h1 dir="rtl" lang='AR' class="cover-heading">أعْـــربْ لـي.</h1>
            <p dir="rtl" lang='AR' class="lead">يُرْجَى تَشْكِيلُ الجُمْلَةِ.</p>
        
        <form name="myForm" method="POST" action="{% url 'process' %}" onsubmit="return validateForm()" required style="margin-bottom: auto; margin-top: auto;" id="sent_in">
            {% csrf_token %}
            <div class="row">
            <div class="col-lg-12">
                <div class="input-group">
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="أعْربْ"></button>
                    </span>
                <input dir="rtl" lang='AR' type="text" class="form-control" name="sent_text" placeholder="هنا يتم إدخال الجملة المراد إعرابها...">
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
            </div>
            
        </form>
    
    {% block 'results' %}
    {% if proposition %}
    <div class="div_results h-75">
        <table id="results" class="table table-bordered">
            <thead>
                <tr>
                    <th style="text-align: center;">الإقتراح</th>
                    <th style="text-align: center;">الكلمة</th>
                    <th style="text-align: center;">إعرابها</th>
                    <th style="text-align: center;">إختيار</th>
                </tr>
            </thead>
            <tbody>
            {% for combination in accepted %}
                {% for irab in combination.proposition %}
                    <tr>
                        {% ifchanged %}<td rowspan={{ phrase|length }} style="text-align: center;">{{ forloop.parentloop.counter }}</td>{% endifchanged %}
                        <td style="text-align: center;">{{ irab.word }}</td>
                        <td style="text-align: right;">{{ irab.irab }}</td>
                        {% ifchanged %}
                            <td rowspan={{ phrase|length }} style="text-align: center;">
                                <a href="{% url 'validate' combination.trans|join:"," %}"><i style="color:green" class="fas fa-check-circle fa-2x"></i><a/>
                            </td>
                        {% endifchanged %}
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th style="text-align: center;">الإقتراح</th>
                    <th style="text-align: center;">الكلمة</th>
                    <th style="text-align: center;">إعرابها</th>
                    <th style="text-align: center;">إختيار</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <br><br>
    {% endif %}
    {% endblock %}
{% endblock %}
{% block 'js' %}
    <script>
        document.querySelector('#nav_home').classList += ' active'
        function validateForm() {
        var x = document.forms["myForm"]["sent_text"].value;
        if (x == "") {
            alert("يرجى إدخال جملة.");
            return false;
        }
        }
    </script>
{% endblock %}

irib/templates/irib/missing_pos.html
{% extends 'index.html' %}

{% block 'content' %}
    <p dir="rtl" lang='AR'>
    <div>
    Decoupage : <br>
    {{out_dec}}<br>
    Recherche du schème : <br>
    {{out_sch}}<br>
    Recherche de la racine : <br>
    {{out_rcn}}<br>
    </div>
    لم يتمكَّن البرنامج من تحليل كلمة {{ missing_word }}<br>
    قد تم تسجيل الكلمة و سنحاول إيجاد حل للمشكل في أقرب وقت إن شاء الله.<br>
    نشكركم على تفهمكم وندعوكم لمواصلة إكتشاف البرنامج.<br>
    <a href="{% url 'home' %}">العودة للصفحة الرئيسية<a>
    </p>
{% endblock %}

irib/templates/irib/process.html
{% extends 'index.html' %}

{% block 'content' %}
    <h1 dir="rtl" lang='AR' class="cover-heading">أعْـــربْ لـي.</h1>
    <div class="div_results">
        <table dir="rtl" lang='AR' id="results" class="table table-bordered">
            <thead>
                <tr>
                    <th style="text-align: center;">الإقتراح</th>
                    <th style="text-align: center;">الكلمة</th>
                    <th style="text-align: center;">إعرابها</th>
                    <th style="text-align: center;">إختيار</th>
                </tr>
            </thead>
            <tbody>
            {% for combination in accepted %}
                {% for irab in combination.proposition %}
                    <tr>
                        {% ifchanged %}<td rowspan={{ phrase|length }} style="text-align: center;">{{ forloop.parentloop.counter }}</td>{% endifchanged %}
                        <td style="text-align: center;">{{ irab.word }}</td>
                        <td style="text-align: right;">{{ irab.irab }}</td>
                        {% ifchanged %}
                            <td rowspan={{ phrase|length }} style="text-align: center;">
                                <a href="{% url 'validate' combination.trans|join:"," %}"><i style="color:green" class="fas fa-check-circle fa-2x"></i><a/>
                            </td>
                        {% endifchanged %}
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th style="text-align: center;">الإقتراح</th>
                    <th style="text-align: center;">الكلمة</th>
                    <th style="text-align: center;">إعرابها</th>
                    <th style="text-align: center;">إختيار</th>
                </tr>
            </tfoot>
        </table>
    <p dir="rtl" lang='AR'>
        بعد اللإطلاع على النتائج و لمنح البرنامج إمكانية التعلم من الأجوبة الصحيحة :
        يُطلب من المستعمل الإختيار ما بين الإقتراحات المطروحة.<br>
        إن لم يتم طرح اللإعراب الصحيح : 
        <a href="{% url 'feed' txt_phrase start_state.id 0 %}">يرجى الضغط هنا لإدخال الإعراب الصحيح.</a>
    </p>
    </div>
    <br><br>
{% endblock %}
{% block 'js' %}
    <script>
        document.querySelector('#nav_results').classList += ' active'
    </script>
{% endblock %}